kind: pipeline
type: docker
name: default

workspace:
  base: /temp
  path: /workdir

steps:
  - name: install dependencies
    image: node:12.13.1
    commands:
      - npm install

  - name: build
    image: node:12.13.1
    commands:
      - npm run build

  - name: generate key
    image: node:12.13.1
    commands:
      - echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
  
  - name: deploy
    image: drillster/drone-rsync
    hosts: [ "35.221.79.212" ]
    key:
      from_secret: SSH_PRIVATE_KEY
    user: verhichi
    source: /workdir/dist/
    target: ~/web

trigger:
  branch:
    - master
  event:
    - push