kind: pipeline
type: docker
name: default

workspace:
  base: /temp
  path: /workdir

steps:
  - name: install dependencies
    image: node:12.13.1
    commands:
      - npm install

  - name: build
    image: node:12.13.1
    commands:
      - npm run build
  
  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: 35.221.79.212
      port: 22
      user: verhichi
      key:
        from_secret: SSH_PRIVATE_KEY
      source: /workdir/dist/
      target: ~/web

trigger:
  branch:
    - master
  event:
    - push